name: Reusable Deploy

on:
  workflow_call:
    inputs:
      image_name:
        description: "Nom de l'image (ex: mon-app)"
        required: true
        type: string
      compose_path:
        description: "Chemin du dossier docker-compose sur le serveur"
        required: true
        type: string
      registry:
        description: "URL du registry"
        required: false
        type: string
        default: "registry.redyd.dev"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: redlab

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.registry }}/${{ inputs.image_name }}:latest
            ${{ inputs.registry }}/${{ inputs.image_name }}:${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ inputs.compose_path }}
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
